# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 UCT Prague.
#
# oarepo-validate is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

dist: focal

sudo: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

python:
  - '3.8'


before_install:
  - travis_retry pip install --upgrade pip setuptools py
  - "travis_retry pip install twine wheel coveralls requirements-builder pip-tools"
  - "requirements-builder --level=pypi -e tests setup.py > .travis-release-requirements.in"
  - "pip-compile -U --verbose -o .travis-release-requirements.txt .travis-release-requirements.in"
  - cat .travis-release-requirements.txt

install:
  - travis_retry pip install -r .travis-release-requirements.txt

script:
  - "./run-tests.sh"

after_success:
  - coveralls

# check if release tag is the same as version.py tag
before_deploy:
  - |-
    SRCTAG=$(cat oarepo_taxonomies/version.py | grep '__version__' | sed 's/__version__//' | sed 's/=//g' | sed 's/"//g' | sed "s/'//g" | sed 's/[ \t\n]//g')
    test $SRCTAG == $TRAVIS_TAG
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "rsI2sh6GOpZiJjJuhl/1Hou62Liu0LI375wFOPcsWcJPfe6rSRGc83rM89hF1cFq144A+qWDIg20yeLUFb4Ovkle/QnYjwmaJ1HlNPzLhq5nlTcPZyl/E7KdhSnljQNViHc6Lpe+JkrwzIj3NX7QW6tucSps09ur3ZemAi5+cmqwbuIeJNrVoDvQES5ADaAPDWHODgcmjSe8qfR9XoQQffsZL7R3q1GbIkjtY5ddU/JhQDbbd7wI5aHqNya2Do/cOmHEMuyxUIIl9iUig6r7v8t9Nc2TlIzHeimBBJKVdXcSsZIGtg6B8bVd0PJozUAWSIC74YJV1VZqG75gl+8aHQ9fg1FMJanaOI6tQCkJYo8FskdFaRLLmX9vkVjHiNNejTBzepfbIJ5SlTY8Ju/SAlquGWAQpQ1k4GfwF1GUgZsqEKitJNLNNv4Hk298QSU1GJOB2zhNKIiyLKuaj/uox5Hy67j6hFBb5cqzO8tbdUvk5mF9EYFY2u3exwFpMu/oLXF/i/e1uaQ9Hs17nr/VXhHKYaFLcv8hcJuq/T2KUzTdrMD9CVywIEbWyVej2EpD3iADJoDJ2Gmtr4NSaDsBJta3s7n8ZG11CxZc6TvjgcizSKJ1ngbFAF/pGnVWTUIgmk51L9u06sZ0jJmGSi97h8I+ddA0NU5kMU315CrhOtM="
  on:
    tags: true
    branch: master
  distributions: "sdist bdist_wheel"
  skip_existing: true